# Sentry Organization Configuration
organization:
  slug: paywithring
  name: PayWithRing
  api_base_url: https://sentry.io/api/0

# Project Filtering Rules
projects:
  # Include all projects by default
  include_all: true
  
  # Optional: Exclude specific projects
  exclude:
    - "test-project"
    - "staging-project"
  
  # Optional: Include only specific projects
  include:
    # - "specific-project-1"
    # - "specific-project-2"

# Environment Configuration
environments:
  production:
    name: "production"
    filter_enabled: true
  
  staging:
    name: "staging"
    filter_enabled: false
  
  development:
    name: "development"
    filter_enabled: false

# API Configuration
api:
  rate_limit_delay: 1  # seconds
  max_retries: 3
  timeout: 30  # seconds
  user_agent: "SentryAlertAutomation/1.0"

# Alert Rule Templates
alert_templates:
  escalating_issue:
    name: "Escalating Issues Alert"
    description: "Alert when issues enter escalating state in production"
    conditions:
      - field: "event.type"
        operator: "eq"
        value: "error"
      - field: "event.status"
        operator: "eq"
        value: "escalating"
    filters:
      - field: "environment"
        operator: "eq"
        value: "production"
    actions:
      - type: "slack"
        channel: "#sentry-alerts"
        message_template: |
          🚨 *Escalating Issue Alert*
          *Project:* {project}
          *Environment:* {environment}
          *Issue:* {issue_title}
          *URL:* {issue_url}
          *Time:* {timestamp} 